config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  namespace :api, defaults: {format: :json} do
    resources :movies, only: [:index]
    resources :seasons, only: [:index]
    resources :items, only: [:index]
    resources :users, only: [] do
      resources :purchases, only: [:create]
    end
    get '/user/:user_id/library' => 'users#library', as: :user_library
  end

  namespace :admin do
    root 'application#index'
    resources :users
    resources :movies
    resources :seasons do
      resources :episodes, except: :index
    end
  end

end

app/models/season.rb
class Season < Item
  has_many :episodes, -> { order(:number) },
    dependent: :delete_all

  validates :title, presence: true
  validates :plot, presence: true

  scope :list, -> { includes(:episodes).order(created_at: :desc) }
end

app/controllers/admin/seasons_controller.rb
class Admin::SeasonsController < Admin::ApplicationController
  before_action :set_season, only: [:show, :edit, :update, :destroy]
  def index
    @seasons = Season.all
  end

  def show
  end

  def new
    @season = Season.new
  end

  def create
    @season = Season.new(season_params)
    if @season.save
      flash[:notice] = "Season has been created."
      redirect_to [:admin, @season]
    else
      flash.now[:alert] = "Season has not been created."
      render 'new'
    end
  end

  def edit
  end

  def update
    if @season.update(season_params)
      flash[:notice] = "Season has been updated."
      redirect_to [:admin, @season]
    else
      flash.now[:alert] = "Season has not been updated."
      render 'edit'
    end
  end

  def destroy
    @season.destroy
    flash[:notice] = "Season has been deleted."
    redirect_to admin_seasons_url
  end



  private

  def set_season
    @season = Season.find(params[:id])
  rescue
    flash[:alert] = "The season you were looking for could not be found."
    redirect_to admin_seasons_url
  end

  def season_params
    params.require(:season).permit(:title, :plot)
  end
end

app/controllers/api/seasons_controller.rb
class API::SeasonsController < API::ApplicationController
  def index
    seasons = Season.list.page(params[:page]).per(params[:per_page])
    render json: seasons, meta: pagination(seasons, params[:per_page])
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_season, only: [:show, :edit, :update, :destroy]
  def index
    @seasons = Season.all
  end

  def show
  end

  def new
    @season = Season.new
  end

  def create
    @season = Season.new(season_params)
    if @season.save
      flash[:notice] = "Season has been created."
      redirect_to @season
    else
      flash.now[:alert] = "Season has not been created."
      render 'new'
    end
  end

  def edit
  end

  def update
    if @season.update(season_params)
      flash[:notice] = "Season has been updated."
      redirect_to @season
    else
      flash.now[:alert] = "Season has not been updated."
      render 'edit'
    end
  end

  def destroy
    @season.destroy
    flash[:notice] = "Season has been deleted."
    redirect_to seasons_url
  end



  private

  def set_season
    @season = Season.find(params[:id])
  rescue
    flash[:alert] = "The season you were looking for could not be found."
    redirect_to seasons_url
  end

  def season_params
    params.require(:season).permit(:title, :plot)
  end
end

app/views/admin/seasons/_form.html.erb
<%= simple_form_for [:admin, @season] do |f| %>
    <%= f.input :title %>
    <%= f.input :plot %>
    <%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/admin/seasons/edit.html.erb
<header>
    <h1>Edit Season</h1>
</header>
<%= render "form", season: @season %>

app/views/admin/seasons/index.html.erb
<header>
    <h1>Seasons</h1>

    <ul class="actions">
        <li><%= link_to "New Season", new_admin_season_path, class: "new" %></li>
    </ul>
</header>


<div id="seasons">
    <% @seasons.each do |season| %>
        <h2><%= link_to season.title, [:admin, season] %></h2>
        <p><%= season.plot %></p>
    <% end %>
</div>

app/views/admin/seasons/new.html.erb
<header>
    <h1>New Season</h1>
</header>
<%= render "form", season: @season %>

app/views/admin/seasons/show.html.erb
<% title(@season.title) %>
<header>
    <h1><%= @season.title %></h1>

    <ul class="actions">
        <li>
            <%= link_to "Edit Season", edit_admin_season_path(@season), class: "edit" %>
        </li>
        <li>
            <%= link_to "Delete Season", admin_season_path(@season),
                method: :delete,
                data: {confirm: "Are you sure you want to delete this season?"},
                class: "delete" %>
        </li>
    </ul>
</header>
<%= simple_format(@season.plot) %>

<header>
    <h2>Episodes</h2>
    <ul class="actions">
        <li>
            <%= link_to "New Episode", new_admin_season_episode_path(@season), class: 'new' %>
        </li>
    </ul>
</header>
<ul id="episodes">
    <% @season.episodes.each do |episode| %>
        <li>
            <%= link_to "#{episode.number} - #{episode.title}", [:admin, @season, episode] %>
        </li>
    <% end %>
</ul>