config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  namespace :api, defaults: {format: :json} do
    resources :movies, only: [:index]
    resources :seasons, only: [:index]
    resources :items, only: [:index]
    resources :users, only: [] do
      resources :purchases, only: [:create]
    end
    get '/user/:user_id/library' => 'users#library', as: :user_library
  end

  namespace :admin do
    root 'application#index'
    resources :users
    resources :movies
    resources :seasons do
      resources :episodes, except: :index
    end
  end

end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  #TODO: implement authorization for the admin site
  def index
  end
end

app/controllers/api/application_controller.rb
class API::ApplicationController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  #TODO: implement authorization for the admin site

  protected
  def pagination(paginated_array, per_page)
    {
      pagination: {
        per_page: per_page.to_i,
        current_page: paginated_array.current_page,
        total_pages: paginated_array.total_pages,
        total_objects: paginated_array.total_count
      }
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Videoclub").join(" - ")
      end
    end
  end
end

app/views/admin/application/index.html.erb
<div class="row" id="admin">
    <div class="col-md-9">
        <header>
            <h1>Admin</h1>
        </header>
    </div>
    <div class="col-md-3">
        <h2>Admin links</h2>
        <ul class="nav nav-stacked">
            <li><%= link_to "Movies", admin_movies_path %></li>
            <li><%= link_to "Seasons", admin_seasons_path %></li>
            <li><%= link_to "Users", admin_users_path %></li>
        </ul>
    </div>
</div>